mongo:
  image: mongo:4.0
  command: mongod --smallfiles --replSet rs0 --oplogSize 128
  labels:
    io.rancher.scheduler.affinity: nextcloud=True

rocketchat:
  image: rocketchat/rocket.chat:2.3.1
  environment:
    - PORT=3000
    - ROOT_URL=http://localhost:3000
    - MONGO_OPLOG_URL=mongodb://mongo:27017/local
  links:
    - mongo:mongo
  ports:
    - 3000:3000
  labels:
    io.rancher.scheduler.affinity: nextcloud=True