version: '2'

services:

  nextcloud:
    image: nextcloud:17.0.2-apache
    volumes_from:
      - nextcloud-data
    ports:
      - ${NEXTCLOUD_PORT}:80
    links:
      - db:db
      - smtp:smtp
    labels:
      io.rancher.sidekicks: nextcloud-data
      io.rancher.container.hostname_override: container_name

  nextcloud-data:
    image: nextcloud:17.0.2-apache
    entrypoint:
      - /bin/true
    volumes:
      - /var/www/html
    links:
      - db:db
      - smtp:smtp
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.container.hostname_override: container_name

  db:
    image: kartoza/postgis:12.0
    environment:
      ALLOW_IP_RANGE: 0.0.0.0/0
      PGDBNAME: ${POSTGRES_DATABASE}
      PGHOST: localhost
      PGPASSWORD: ${POSTGRES_PASS}
      PGUSER: ${POSTGRES_USER}
      POSTGRES_DBNAME: ${POSTGRES_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_USER: ${POSTGRES_USER}
    labels:
      io.rancher.container.hostname_override: container_name

  smtp:
    image: catatnight/postfix
    environment:
      maildomain: kartoza.com
      smtp_user: noreply:docker
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
